name: Lint

on: [push]
jobs:
  test-execution:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run test
        run: npm install && npm run test
